### ISSUE TITLE
CPU perfomance ios

### ISSUE THREAD

**Issue by Netwolf** [kylemcdonald/FaceTracker#39]
Hello, im having trouble with a high cpu perfomance in iOS. This is causing some delay`s in the face position. Anyone has a advice about that?

**Comment by kylemcdonald** [comment]
FaceTracker has high CPU usage by design. If you are having delays in acquiring the face position, and this is slowing down your app, you should put the face tracker in a separate thread. Alternatively, you might try using the native face detector on iOS and modify FaceTracker to take that as an initialization.
